### ISSUE TITLE
Make Disqus and Google Analytics optional

### ISSUE THREAD

**Issue by petargyurov** [chesterhow/tale#87]
Hi @chesterhow,

First off, great theme; I've decided to use it for my blog.

One little suggestion I would make is to make Disqus and Google Analytics optional. I am not familiar enough with Jekyll to know if you can provide optional build params. 

If not I would probably remove these two from the base repo, especially Google Analytics.

**Comment by chesterhow** [comment]
Hi @petargyurov these features are already optional. They are opt-in rather than opt-out features.
- Your posts will not have Disqus comments enabled unless you add `comments: true` in the frontmatter of that post. 
- There is no Google Analytics tracking enabled unless you add your GA tracking-id in the `_config.yml` file
